### ISSUE TITLE
Changing Name Of the Command

### ISSUE THREAD

**Issue by blaze534** [PetyXbron/minecraft-bot#16]
I want to translate the command in italian when i change the name of the command and the name of the file nothing happens what to do?

**Comment by PetyXbron** [comment]
@blaze534, can you please give me your result? How did you solve this issue?
It can take a while (up to 1 hour) when updating a slash command name.

**Comment by blaze534** [comment]
> @blaze534, can you please give me your result? How did you solve this issue? It can take a while (up to 1 hour) when updating a slash command name.
ok thanks im just stupid and i am a beginner on this so sorry for the disturb  you help me a lot whith this so thanks

**Comment by blaze534** [comment]
@PetyXbron but for waiting the bot need to be on?

**Comment by PetyXbron** [comment]
> @PetyXbron but for waiting the bot need to be on?

@blaze534 _"waiting the bot"_? What do you mean?
If you want to change the name of a shlash command you need to wait a while (up to 1 hour) I am not sure if the bot needs to be online, but it needs to start up with your name update. So I guess you can turn on the bot for 2-3min, then turn it off, and wait for the slash command name change.

**Comment by blaze534** [comment]
@PetyXbron so im waiting but nothing happens when i change the name in the file and rename the file whith the name of the command i need to execute it? because i wait more than an hour and nothing happened do you have some wiki who explain this?

**Comment by PetyXbron** [comment]
**I will answer tomorrow.**
10AM - 18PM (CEST)

**Comment by PetyXbron** [comment]
So basically, if you want to change some command name, **you need to edit config and command file name too**.

So in order to rename the command, you need to go to [`./commands`](https://github.com/PetyXbron/minecraft-bot/tree/400c5c2fd5c2405f68bf7945f50d99ebab174dfd/commands) and rename your file and also change the condition in module.exports.config.name (commonly on line 6 or 8).
After this, you can switch the folder to [`./slashes` ](https://github.com/PetyXbron/minecraft-bot/tree/400c5c2fd5c2405f68bf7945f50d99ebab174dfd/slashes)then rename the file name of your command and also change the string in the slashCommandBuilder function (commonly on line 8 or 10).
And the last thing you have to do is to go to file [`config.js`](https://github.com/PetyXbron/minecraft-bot/blob/400c5c2fd5c2405f68bf7945f50d99ebab174dfd/config.js) and find your command in the [`commands` object](https://github.com/PetyXbron/minecraft-bot/blob/400c5c2fd5c2405f68bf7945f50d99ebab174dfd/config.js#L94). You need to rename the object like on the attached image.
![image](https://user-images.githubusercontent.com/35902119/192148509-3c3476fa-a148-4542-8a37-ae655521578b.png)

**Then turn on your bot for 1-2 minutes and wait for command name updates.** (Normal [chat] command updates immediately, slash commands take a while because of Discord API)
