### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by blaze534** [PetyXbron/minecraft-bot#17]
minecraft-bot-main\slashes\status.js:126
                if (warns) console.log(`${bot.emotes.warn} ` + warn(`Error when using command ${module.exports.config.name}! Error:\n`) + error);
                                                                                                                      ^

TypeError: Cannot read properties of undefined (reading 'name')
    at C:\Users\Utente\Desktop\BOTS\minecraft-bot-main\slashes\status.js:126:119
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

i was thinking it was my bug but when i reinstalled it its the same @PetyXbron

**Comment by PetyXbron** [comment]
Yeah, this is a project problem. Mistake in the code. I will try to fix it in a new update.

**Comment by blaze534** [comment]
ok thanks

**Comment by blaze534** [comment]
when is gonna be out the new update?

**Comment by PetyXbron** [comment]
> when is gonna be out the new update?
> 

I will of course try to update it as soon as possible. Maybe tomorrow, but unfortunately I can't guarantee it.

**Comment by PetyXbron** [comment]
I know why this bug was not reported earlier. This log only shows when you have warns option in your config enabled and probably most of the users don't have it enabled.
**However, it is fixed.** Please updated your code. **Version** [**[1.6.8]**](https://github.com/PetyXbron/minecraft-bot/commit/12eb91b2494c40f8a91e14ccb24b23d126319b73) has updated [list.js](https://github.com/PetyXbron/minecraft-bot/blob/12eb91b2494c40f8a91e14ccb24b23d126319b73/slashes/list.js) and [status.js](https://github.com/PetyXbron/minecraft-bot/blob/12eb91b2494c40f8a91e14ccb24b23d126319b73/slashes/status.js) in [`/slashes`](https://github.com/PetyXbron/minecraft-bot/tree/12eb91b2494c40f8a91e14ccb24b23d126319b73/slashes), so your process should not be killed again by this error.
