### ISSUE TITLE
Undefined reading 'id'

### ISSUE THREAD

**Issue by MG141** [PetyXbron/minecraft-bot#3]
Having issues with starting up the bot if someone could help me with the fix.
![Screenshot_20220216_113235](https://user-images.githubusercontent.com/65613737/154247253-bc70e75c-3f77-4ab8-8d49-aa7dd3115d69.jpg)

**Comment by PetyXbron** [comment]
If you want to use [statusCH setting](https://github.com/PetyXbron/minecraft-bot/blob/2c3a248a03ba715e1db7d54788648760289dc70a/config.js#L31) enabled, you need to define the other [variables](https://github.com/PetyXbron/minecraft-bot/blob/main/config.js#L56-L65). Did you set these?
And did you invite the bot with official invite link - https://discord.com/oauth2/authorize?client_id=**BOTUSERIDHERE**&permissions=274877918272&scope=bot%20applications.commands ? Maybe the bot doesn't have permission to send messages in your status channel and also try to check the channel permissions for the bot's role.

**Comment by PetyXbron** [comment]
@MG141, are you still facing this problem?

**Comment by BalesDot** [comment]
i am facing this problem

**Comment by PetyXbron** [comment]
The bot could not send the statusCH message. Check the bot's permissions or re-invite it with the official link in the console.
If you are interested in faster support response and deeper help, consider joining [this project Discord support server](https://discord.com/invite/PYTqqhWad2).

**Comment by PetyXbron** [comment]
Hey everyone, if you are facing this issue we found a new possible solution. **Please check if you have all dependencies updated as the version you are using includes in [package.json file](https://github.com/PetyXbron/minecraft-bot/blob/main/package.json).**
It may be caused especially because of the discord.js and a new syntax for sending messages.
Also, it may help you to update to dev version [1.6.9.2](https://github.com/PetyXbron/minecraft-bot/commit/c9929712585fd6467661f7704a787db45a851d01) or higher because there is a new saving system and you won't face issues with quick.db, which was in some cases unsupported (e.g. in hosting).
